# Generated by Django 4.0.4 on 2022-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
