# Generated by Django 4.0.4 on 2022-05-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0002_alter_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.IntegerField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
