# Generated by Django 4.0.4 on 2022-05-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0004_roomtypes_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
