# Generated by Django 4.0.4 on 2022-05-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0005_hotel_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomTypes',
            new_name='RoomType',
        ),
    ]
