# Generated by Django 4.0.4 on 2022-05-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotels', '0006_rename_roomtypes_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('logo', models.CharField(blank=True, default='', max_length=300)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hotels.company'),
        ),
    ]
