# Generated by Django 4.0.4 on 2022-05-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0007_hotel_description_hotel_image_roomtype_image_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='company',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Hotels.company'),
        ),
    ]
