# Generated by Django 4.0.4 on 2022-05-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0009_conglomerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conglomerate',
        ),
    ]
