# Generated by Django 4.0.4 on 2022-05-14 07:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotels', '0010_delete_conglomerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 2, 15, 40, 670588))),
                ('date_update', models.DateTimeField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.room')),
            ],
        ),
    ]
