# Generated by Django 4.0.4 on 2022-05-14 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0011_room_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='available',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 8, 29, 49, 138892)),
        ),
    ]
