# Generated by Django 4.0.4 on 2022-05-14 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0015_alter_reservation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 17, 54, 54, 731523)),
        ),
    ]
