# Generated by Django 4.0.4 on 2022-05-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0017_alter_reservation_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
