# Generated by Django 4.0.4 on 2022-05-14 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotels', '0018_remove_room_roomtype_delete_reservation_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_fn', models.CharField(max_length=100)),
                ('customer_ln', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 5, 8, 844602))),
                ('date_update', models.DateTimeField(default=None)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.roomtype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
