# Generated by Django 4.0.4 on 2022-05-14 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0019_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 19, 41, 51267)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
