# Generated by Django 4.0.4 on 2022-05-14 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0020_alter_reservation_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 19, 59, 453141)),
        ),
    ]
