# Generated by Django 4.0.4 on 2022-05-15 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0022_alter_reservation_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 20, 35, 20, 870559)),
        ),
    ]
