# Generated by Django 4.0.4 on 2022-05-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0026_alter_reservation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roomtype',
            field=models.CharField(max_length=50),
        ),
    ]
