# Generated by Django 4.0.4 on 2022-05-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0027_reservation_hotel_name_alter_reservation_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='company',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
