# Generated by Django 4.0.4 on 2022-05-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0028_reservation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
